[package]
name = "fu740-pac"
version = "0.1.0"
authors = ["The RISC-V Team <risc-v@teams.rust-embedded.org>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Peripheral access API for FU740 SoC"
keywords = ["no-std", "riscv", "register", "peripheral"]
license = "ISC"
edition = "2018"

[dependencies]
bare-metal = "0.2.4"
riscv = "0.5.0"
riscv-rt = { version = "0.5.0", optional = true }
vcell = "0.1.0"

[features]
rt = ["riscv-rt"]
